name       : perl-business-isbn
version    : 3.004
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.004.tar.gz : 31754acd57bf0c3d4762003d784bce4a0af6832a725336e219fb2988b6fb831e
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN - work with International Standard Book Numbers
description: |
    Business::ISBN - work with International Standard Book Numbers
builddeps  :
    - perl
rundeps    :
    - perl-business-isbn-data
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
