name       : perl-business-isbn
version    : '3.008'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.008.tar.gz : 19c4a1d4d99a0dd7695a90192b13404a0e3eeebedfcbe97a0202e36b238c0e69
homepage   : https://metacpan.org/pod/Business::ISBN
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN - work with International Standard Book Numbers
description: |
    This modules handles International Standard Book Numbers, including ISBN-10 and ISBN-13. The data come from Business::ISBN::Data, which means you can update the data separately from the code. Also, you can use Business::ISBN::Data with whatever RangeMessage.xml you like if you have updated data. See that module for details.
builddeps  :
    - perl
rundeps    :
    - perl-business-isbn-data
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
