name       : perl-business-isbn
version    : '3.005'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.005.tar.gz : 6530fbae40c56376db4e6686c34af8da3db5c4baad0d104047b1ef3e24fe2e2a
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN - work with International Standard Book Numbers
description: |
    Business::ISBN - work with International Standard Book Numbers
builddeps  :
    - perl
rundeps    :
    - perl-business-isbn-data
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
